[tool.poetry]
name = "mlb-display"
version = "0.1.0"
description = ""
authors = ["hiemenz <kevinhiemenz1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pillow = "^11.1.0"
requests = "^2.31.0"
pytz = "^2024.1"
regex = "^2026.1.15"
pyyaml = "^6.0.0"
pyreadr = "^0.5.4"
imageio = {extras = ["ffmpeg"], version = "^2.37.3", python = ">=3.10"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
